/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './board.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../../../../../src/app/lib/range.pipe';
import * as import3 from '@angular/common';
import * as import4 from '../../../../../src/app/bingo/board/board.component';
const styles_BingoBoardComponent:any[] = [import0.styles];
export const RenderType_BingoBoardComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_BingoBoardComponent,
  data: {}
}
);
function View_BingoBoardComponent_1(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
      (l()(),import1.ɵeld(0,(null as any),(null as any),1,'div',([] as any[]),[[
        2,
        'board-selected-bingo-number',
        (null as any)
      ]
    ],(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),[
      '',
      ''
    ]
    ))
  ]
  ,(null as any),(ck,v) => {
    var co:any = v.component;
    const currVal_0:any = co.state.used[v.context.$implicit];
    ck(v,0,0,currVal_0);
    const currVal_1:any = v.context.$implicit;
    ck(v,1,0,currVal_1);
  });
}
export function View_BingoBoardComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    import1.ɵpid(0,import2.RangePipe,([] as any[])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),5,'div',[[
        'class',
        'bingo-board'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n    '])),
    (l()(),import1.ɵand(8388608,(null as any),(null as any),2,(null as any),View_BingoBoardComponent_1)),
    import1.ɵdid(401408,(null as any),0,import3.NgForOf,[
      import1.ViewContainerRef,
      import1.TemplateRef,
      import1.IterableDiffers
    ]
      ,{ngForOf: [
        0,
        'ngForOf'
      ]
    },(null as any)),
    import1.ɵppd(2),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    const currVal_0:any = import1.ɵunv(v,4,0,ck(v,5,0,import1.ɵnov(v,0),import1.ɵEMPTY_ARRAY,100));
    ck(v,4,0,currVal_0);
  },(null as any));
}
function View_BingoBoardComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'bingo-board',([] as any[]),(null as any),(null as any),(null as any),View_BingoBoardComponent_0,RenderType_BingoBoardComponent)),
    import1.ɵdid(57344,(null as any),0,import4.BingoBoardComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const BingoBoardComponentNgFactory:import1.ComponentFactory<import4.BingoBoardComponent> = import1.ɵccf('bingo-board',import4.BingoBoardComponent,View_BingoBoardComponent_Host_0,{glob: 'glob'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQW50aG9ueS9Eb2N1bWVudHMvR2l0SHViL2FuZ3VsYXIvYmluZ28vc3JjL2FwcC9iaW5nby9ib2FyZC9ib2FyZC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvQW50aG9ueS9Eb2N1bWVudHMvR2l0SHViL2FuZ3VsYXIvYmluZ28vc3JjL2FwcC9iaW5nby9ib2FyZC9ib2FyZC5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9BbnRob255L0RvY3VtZW50cy9HaXRIdWIvYW5ndWxhci9iaW5nby9zcmMvYXBwL2JpbmdvL2JvYXJkL2JvYXJkLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvQW50aG9ueS9Eb2N1bWVudHMvR2l0SHViL2FuZ3VsYXIvYmluZ28vc3JjL2FwcC9iaW5nby9ib2FyZC9ib2FyZC5jb21wb25lbnQudHMuQmluZ29Cb2FyZENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJiaW5nby1ib2FyZFwiPlxyXG4gICAgPGRpdiAqbmdGb3I9XCJsZXQgbiBvZiBbXSB8IHJhbmdlOjEwMFwiIFtjbGFzcy5ib2FyZC1zZWxlY3RlZC1iaW5nby1udW1iZXJdPVwic3RhdGUudXNlZFtuXVwiPnt7bn19PC9kaXY+XHJcbjwvZGl2PiIsIjxiaW5nby1ib2FyZD48L2JpbmdvLWJvYXJkPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7TUNDSTtRQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBMEY7TUFBQTtNQUFBO0lBQUE7SUFBQTs7OztJQUFwRDtJQUF0QyxTQUFzQyxTQUF0QztJQUEwRjtJQUFBOzs7Ozs7TUFEOUY7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUF5QjtJQUNyQjtnQkFBQTs7OztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtnQkFBSztJQUFnRzs7O0lBQWhHO0lBQUwsU0FBSyxTQUFMOzs7OztJQ0RKO2dCQUFBOzs7SUFBQTs7OyJ9
