/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.bingo-board[_ngcontent-%COMP%] {\r\n    border: 3px solid #88f;\r\n    border-radius: 10px;\r\n    display: flex;\r\n    flex-wrap: wrap;\r\n    width: calc(40em + 8px * 41);\r\n}\r\n\r\n.bingo-board[_ngcontent-%COMP%]   div[_ngcontent-%COMP%] {\r\n    border: 1px solid #000;\r\n    border-radius: 5px;\r\n    width: 2em;\r\n    height: 2em;\r\n    padding: .25em;\r\n    margin: 8px;\r\n    text-align: center;\r\n}\r\n\r\n.board-selected-bingo-number[_ngcontent-%COMP%] {\r\n    background-color: #8b8;\r\n    color: #fff;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQW50aG9ueS9Eb2N1bWVudHMvR2l0SHViL2FuZ3VsYXIvYmluZ28vc3JjL2FwcC9iaW5nby9ib2FyZC9ib2FyZC5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL0FudGhvbnkvRG9jdW1lbnRzL0dpdEh1Yi9hbmd1bGFyL2JpbmdvL3NyYy9hcHAvYmluZ28vYm9hcmQvYm9hcmQuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
