/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './status.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../../../../../src/app/bingo/status/status.component';
const styles_BingoStatusComponent:any[] = [import0.styles];
export const RenderType_BingoStatusComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_BingoStatusComponent,
  data: {}
}
);
export function View_BingoStatusComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),4,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n    '])),
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),[
      '',
      ''
    ]
    )),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(null as any),(ck,v) => {
    var co:import2.BingoStatusComponent = v.component;
    const currVal_0:any = co.state.status;
    ck(v,3,0,currVal_0);
  });
}
function View_BingoStatusComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'bingo-status',([] as any[]),(null as any),(null as any),(null as any),View_BingoStatusComponent_0,RenderType_BingoStatusComponent)),
    import1.ɵdid(57344,(null as any),0,import2.BingoStatusComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const BingoStatusComponentNgFactory:import1.ComponentFactory<import2.BingoStatusComponent> = import1.ɵccf('bingo-status',import2.BingoStatusComponent,View_BingoStatusComponent_Host_0,{glob: 'glob'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQW50aG9ueS9Eb2N1bWVudHMvR2l0SHViL2FuZ3VsYXIvYmluZ28vc3JjL2FwcC9iaW5nby9zdGF0dXMvc3RhdHVzLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9BbnRob255L0RvY3VtZW50cy9HaXRIdWIvYW5ndWxhci9iaW5nby9zcmMvYXBwL2JpbmdvL3N0YXR1cy9zdGF0dXMuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvQW50aG9ueS9Eb2N1bWVudHMvR2l0SHViL2FuZ3VsYXIvYmluZ28vc3JjL2FwcC9iaW5nby9zdGF0dXMvc3RhdHVzLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvQW50aG9ueS9Eb2N1bWVudHMvR2l0SHViL2FuZ3VsYXIvYmluZ28vc3JjL2FwcC9iaW5nby9zdGF0dXMvc3RhdHVzLmNvbXBvbmVudC50cy5CaW5nb1N0YXR1c0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXY+XHJcbiAgICA8cD57e3N0YXRlLnN0YXR1c319PC9wPlxyXG48L2Rpdj4iLCI8YmluZ28tc3RhdHVzPjwvYmluZ28tc3RhdHVzPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7SUFBSztJQUNEO0lBQUc7TUFBQTtNQUFBO0lBQUE7SUFBQTtJQUFvQjs7OztJQUFwQjtJQUFBOzs7OztJQ0RQO2dCQUFBOzs7SUFBQTs7OyJ9
