/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQW50aG9ueS9Eb2N1bWVudHMvR2l0SHViL2FuZ3VsYXIvYmluZ28vc3JjL2FwcC9iaW5nby9zdGF0dXMvc3RhdHVzLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvQW50aG9ueS9Eb2N1bWVudHMvR2l0SHViL2FuZ3VsYXIvYmluZ28vc3JjL2FwcC9iaW5nby9zdGF0dXMvc3RhdHVzLmNvbXBvbmVudC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
