/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQW50aG9ueS9Eb2N1bWVudHMvR2l0SHViL2FuZ3VsYXIvYmluZ28vc3JjL2FwcC9iaW5nby9jb250cm9scy9jb250cm9scy5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL0FudGhvbnkvRG9jdW1lbnRzL0dpdEh1Yi9hbmd1bGFyL2JpbmdvL3NyYy9hcHAvYmluZ28vY29udHJvbHMvY29udHJvbHMuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
