/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './controls.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../../../../../src/app/bingo/controls/controls.component';
const styles_BingoControlsComponent:any[] = [import0.styles];
export const RenderType_BingoControlsComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_BingoControlsComponent,
  data: {}
}
);
export function View_BingoControlsComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),7,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n    '])),
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'button',[
      [
        'class',
        'btn btn-info'
      ]
      ,
      [
        'type',
        'button'
      ]

    ]
      ,(null as any),[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:import2.BingoControlsComponent = v.component;
      if (('click' === en)) {
        const pd_0:any = ((<any>co.next()) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['Next number'])),
    (l()(),import1.ɵted((null as any),['\n    '])),
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'button',[
      [
        'class',
        'btn btn-danger'
      ]
      ,
      [
        'type',
        'button'
      ]

    ]
      ,(null as any),[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:import2.BingoControlsComponent = v.component;
      if (('click' === en)) {
        const pd_0:any = ((<any>co.reset()) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['Reset'])),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(null as any),(null as any));
}
function View_BingoControlsComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'bingo-controls',([] as any[]),(null as any),(null as any),(null as any),View_BingoControlsComponent_0,RenderType_BingoControlsComponent)),
    import1.ɵdid(57344,(null as any),0,import2.BingoControlsComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const BingoControlsComponentNgFactory:import1.ComponentFactory<import2.BingoControlsComponent> = import1.ɵccf('bingo-controls',import2.BingoControlsComponent,View_BingoControlsComponent_Host_0,{glob: 'glob'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQW50aG9ueS9Eb2N1bWVudHMvR2l0SHViL2FuZ3VsYXIvYmluZ28vc3JjL2FwcC9iaW5nby9jb250cm9scy9jb250cm9scy5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvQW50aG9ueS9Eb2N1bWVudHMvR2l0SHViL2FuZ3VsYXIvYmluZ28vc3JjL2FwcC9iaW5nby9jb250cm9scy9jb250cm9scy5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9BbnRob255L0RvY3VtZW50cy9HaXRIdWIvYW5ndWxhci9iaW5nby9zcmMvYXBwL2JpbmdvL2NvbnRyb2xzL2NvbnRyb2xzLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvQW50aG9ueS9Eb2N1bWVudHMvR2l0SHViL2FuZ3VsYXIvYmluZ28vc3JjL2FwcC9iaW5nby9jb250cm9scy9jb250cm9scy5jb21wb25lbnQudHMuQmluZ29Db250cm9sc0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXY+XHJcbiAgICA8YnV0dG9uIHR5cGU9XCJidXR0b25cIiBjbGFzcz1cImJ0biBidG4taW5mb1wiIChjbGljayk9XCJuZXh0KClcIj5OZXh0IG51bWJlcjwvYnV0dG9uPlxyXG4gICAgPGJ1dHRvbiB0eXBlPVwiYnV0dG9uXCIgY2xhc3M9XCJidG4gYnRuLWRhbmdlclwiIChjbGljayk9XCJyZXNldCgpXCI+UmVzZXQ8L2J1dHRvbj5cclxuPC9kaXY+IiwiPGJpbmdvLWNvbnRyb2xzPjwvYmluZ28tY29udHJvbHM+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUFLO0lBQ0Q7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7TUFBQTtNQUFBO01BQTJDO1FBQUE7UUFBQTtNQUFBO01BQTNDO0lBQUE7SUFBNEQ7SUFBb0I7SUFDaEY7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7TUFBQTtNQUFBO01BQTZDO1FBQUE7UUFBQTtNQUFBO01BQTdDO0lBQUE7SUFBK0Q7SUFBYzs7Ozs7O0lDRmpGO2dCQUFBOzs7SUFBQTs7OyJ9
