/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './card.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '@angular/common';
import * as import3 from '../../../../../src/app/bingo/card/card.component';
const styles_BingoCardComponent:any[] = [import0.styles];
export const RenderType_BingoCardComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_BingoCardComponent,
  data: {}
}
);
function View_BingoCardComponent_1(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
      (l()(),import1.ɵeld(0,(null as any),(null as any),1,'div',([] as any[]),[[
        2,
        'card-selected-bingo-number',
        (null as any)
      ]
    ],(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),[
      '',
      ''
    ]
    ))
  ]
  ,(null as any),(ck,v) => {
    var co:any = v.component;
    const currVal_0:any = co.state.used[v.context.$implicit];
    ck(v,0,0,currVal_0);
    const currVal_1:any = v.context.$implicit;
    ck(v,1,0,currVal_1);
  });
}
export function View_BingoCardComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
      (l()(),import1.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'bingo-card'
      ]
      ],[[
        2,
        'is-deactivated-bingo-card',
        (null as any)
      ]
    ],(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n    '])),
    (l()(),import1.ɵand(8388608,(null as any),(null as any),1,(null as any),View_BingoCardComponent_1)),
    import1.ɵdid(401408,(null as any),0,import2.NgForOf,[
      import1.ViewContainerRef,
      import1.TemplateRef,
      import1.IterableDiffers
    ]
      ,{ngForOf: [
        0,
        'ngForOf'
      ]
    },(null as any)),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    var co:import3.BingoCardComponent = v.component;
    const currVal_1:any = co.card.luckyNumbers;
    ck(v,3,0,currVal_1);
  },(ck,v) => {
    var co:import3.BingoCardComponent = v.component;
    const currVal_0:boolean = !co.card.isActive;
    ck(v,0,0,currVal_0);
  });
}
function View_BingoCardComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'bingo-card',([] as any[]),(null as any),(null as any),(null as any),View_BingoCardComponent_0,RenderType_BingoCardComponent)),
    import1.ɵdid(57344,(null as any),0,import3.BingoCardComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const BingoCardComponentNgFactory:import1.ComponentFactory<import3.BingoCardComponent> = import1.ɵccf('bingo-card',import3.BingoCardComponent,View_BingoCardComponent_Host_0,{
  cardId: 'cardId',
  glob: 'glob'
}
,{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQW50aG9ueS9Eb2N1bWVudHMvR2l0SHViL2FuZ3VsYXIvYmluZ28vc3JjL2FwcC9iaW5nby9jYXJkL2NhcmQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL0FudGhvbnkvRG9jdW1lbnRzL0dpdEh1Yi9hbmd1bGFyL2JpbmdvL3NyYy9hcHAvYmluZ28vY2FyZC9jYXJkLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL0FudGhvbnkvRG9jdW1lbnRzL0dpdEh1Yi9hbmd1bGFyL2JpbmdvL3NyYy9hcHAvYmluZ28vY2FyZC9jYXJkLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvQW50aG9ueS9Eb2N1bWVudHMvR2l0SHViL2FuZ3VsYXIvYmluZ28vc3JjL2FwcC9iaW5nby9jYXJkL2NhcmQuY29tcG9uZW50LnRzLkJpbmdvQ2FyZENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJiaW5nby1jYXJkXCIgW2NsYXNzLmlzLWRlYWN0aXZhdGVkLWJpbmdvLWNhcmRdPVwiIWNhcmQuaXNBY3RpdmVcIj5cclxuICAgIDxkaXYgKm5nRm9yPVwibGV0IG51bWJlciBvZiBjYXJkLmx1Y2t5TnVtYmVyc1wiIFtjbGFzcy5jYXJkLXNlbGVjdGVkLWJpbmdvLW51bWJlcl09XCJzdGF0ZS51c2VkW251bWJlcl1cIj57e251bWJlcn19PC9kaXY+XHJcbjwvZGl2PiIsIjxiaW5nby1jYXJkPjwvYmluZ28tY2FyZD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7TUNDSTtRQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBc0c7TUFBQTtNQUFBO0lBQUE7SUFBQTs7OztJQUF4RDtJQUE5QyxTQUE4QyxTQUE5QztJQUFzRztJQUFBOzs7OztNQUQxRztRQUFBO1FBQUE7TUFBQTtNQUFBO1FBQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUEyRTtJQUN2RTtnQkFBQTs7OztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUFzSDs7OztJQUFqSDtJQUFMLFNBQUssU0FBTDs7O0lBRG9CO0lBQXhCLFNBQXdCLFNBQXhCOzs7OztJQ0FBO2dCQUFBOzs7SUFBQTs7Ozs7OzsifQ==
