/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.bingo-card[_ngcontent-%COMP%] {\r\n    border: 3px solid #f88;\r\n    border-radius: 10px;\r\n    display: flex;\r\n    flex-wrap: wrap;\r\n    padding: 10px;\r\n}\r\n\r\n.bingo-card[_ngcontent-%COMP%]   div[_ngcontent-%COMP%] {\r\n    border: 1px solid #000;\r\n    border-radius: 2px;\r\n    width: 20%;\r\n    padding: 10px;\r\n    text-align: center;\r\n}\r\n\r\n.is-deactivated-bingo-card[_ngcontent-%COMP%], .is-deactivated-bingo-card[_ngcontent-%COMP%]   div[_ngcontent-%COMP%] {\r\n    border-color: #ccc;\r\n    color: #ccc;\r\n}\r\n\r\n.card-selected-bingo-number[_ngcontent-%COMP%] {\r\n    background-color: #8b8;\r\n    color: #fff;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQW50aG9ueS9Eb2N1bWVudHMvR2l0SHViL2FuZ3VsYXIvYmluZ28vc3JjL2FwcC9iaW5nby9jYXJkL2NhcmQuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9BbnRob255L0RvY3VtZW50cy9HaXRIdWIvYW5ndWxhci9iaW5nby9zcmMvYXBwL2JpbmdvL2NhcmQvY2FyZC5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
